### ISSUE TITLE
Problem with  passed target frame to lookupTransform

### ISSUE THREAD

**Issue by ghost** [beltransen/lidar_bev#2]
Hey guys,

After a bit of research, I was able to reduce the error and specify the issue more precisely.

There is a problem with the target frame. In my case, I found out that it is called **yrl_cloud_id.**
After I checked the frame via **rosrun tf view_frames** I get the following PDF output with parent frame and child frame:

![frame_id](https://user-images.githubusercontent.com/102356063/160782957-0ce53d89-8934-42c5-8269-ffd63ee937c8.png)

I pass the frame_id to the param in the file **lidar_bev.cpp**:

![lidar_bev cpp](https://user-images.githubusercontent.com/102356063/160783522-ebc39372-1968-4964-8dc1-a8d0e41128b2.png)

But it still gives me the WARNING, that the target frame, that i passed to lookupTransform (cloud_filter.cpp) doesn't exist. 
**Note:** the ROS_INFO was added by myself.

Why? I receive data from my LiDAR and can visualize them. Should I don't use a launch file or what?

![Terminal messages](https://user-images.githubusercontent.com/102356063/160783343-f260fd1f-3d77-48fe-8739-0ccb8451a9d1.png)

Many thanks for your help!

**Comment by Petros626** [comment]
@ghost still working with this node?
